#!/bin/bash
#read -p "Please input the number of files: " N
#echo "num =$N"
for ((N=1000;N<=10000;N+=1000));
do
	sed -i "24c #define NUM_READ $N" search.cpp;
	g++ -std=c++11 search.cpp -o ./app -L /usr/lib/ -l ssl -l crypto;
	sleep 1;
	./app;
done
